const assert=require('node:assert/strict');
const fs=require('node:fs');
const ts=require('typescript');
const Module=require('node:module');
const m=new Module('fleet',module);
m._compile(ts.transpileModule(fs.readFileSync('lib/fleet.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020}}).outputText,'fleet');
const {emptyFleet,applyFleetAction,assignmentFor,fleetAlerts,documentStatus}=m.exports;
let state=emptyFleet,seq=0;
const now='2026-09-04T12:00:00Z';
const run=action=>state=applyFleetAction(state,action,now,String(++seq));
const driver=(id,name)=>({id,name,phone:'',email:'',group:'Test',active:true,availability:'Disponible',notes:''});
const truck=(id,unit,status='Disponible')=>({id,unit,vin:'',plate:'',plateState:'',year:'',make:'',model:'',type:'',status,notes:''});
run({type:'driver',record:driver('d1','Test Uno'),reason:''});
run({type:'driver',record:driver('d2','Test Dos'),reason:''});
for(const record of [truck('t1','101'),truck('t2','102'),truck('t3','103','En mantenimiento')])run({type:'equipment',kind:'trucks',record,reason:''});
assert.throws(()=>run({type:'equipment',kind:'trucks',record:truck('dup','101'),reason:''}),/existe/);
assert.throws(()=>run({type:'assign',driverId:'d1',truckId:'t3',trailerId:'',reason:'test'}),/disponible/);
run({type:'assign',driverId:'d1',truckId:'t1',trailerId:'',reason:'Primera'});
const old=structuredClone(state),first=assignmentFor(state,'drivers','d1');
assert.throws(()=>run({type:'assign',driverId:'d2',truckId:'t1',trailerId:'',reason:'Conflicto'}),/otro chofer/);
assert.throws(()=>run({type:'driver',record:{...state.drivers[0],active:false},reason:'Baja'}),/Finaliza/);
assert.throws(()=>run({type:'equipment',kind:'trucks',record:{...state.trucks[0],status:'En mantenimiento'},reason:'Taller'}),/Finaliza/);
run({type:'assign',driverId:'d1',truckId:'t2',trailerId:'',reason:'Cambio'});
assert.equal(first.endedAt,undefined);
assert.equal(old.assignments[0].endedAt,undefined);
assert.equal(state.assignments[0].endedAt,now);
assert.equal(state.assignments.length,2);
assert.equal(assignmentFor(state,'trucks','t1'),undefined);
assert.equal(state.events[0].before.truckId,'t1');
assert.equal(state.events[0].after.truckId,'t2');
run({type:'end',id:assignmentFor(state,'drivers','d1').id,reason:'Fin'});
run({type:'driver',record:{...state.drivers[0],active:false},reason:'Baja'});
assert.throws(()=>run({type:'assign',driverId:'d1',truckId:'t1',trailerId:'',reason:'Test'}),/activo/);
run({type:'document',record:{ownerKind:'drivers',ownerId:'d2',type:'Licencia',issued:'2025-01-01',expires:'2026-09-01',reviewed:true,notes:'',filename:'test.pdf',file:new Blob(['%PDF-test'],{type:'application/pdf'})}});
assert.equal(state.documents[0].reviewed,false);
assert.equal(documentStatus(state.documents[0],'2026-09-04'),'Vencido');
assert.ok(fleetAlerts(state,'2026-09-04').some(a=>a.title==='Documento vencido'));
run({type:'reviewDocument',id:state.documents[0].id,reviewed:true,reason:'Comprobado'});
assert.equal(state.documents[0].reviewedAt,now);
assert.equal(documentStatus(state.documents[0],'2026-09-04'),'Vencido');
assert.throws(()=>run({type:'warningDays',days:-1}),/365/);
assert.equal(state.revision,state.events.length);
assert.equal(emptyFleet.drivers.length,0);
console.log('PASS: duplicate equipment, conflicts, availability, immutable assignment history, inactivation, document review, expiry alerts and audit revisions.');
